remix_parameters:
  crossover: 1
  roundts: 1
  timestart: 8
  timeend: 8
  datadir: ../data
  opfmethod: kirchhoff
  scaletimefrac: 0
  
metrics:
  runtime: <=10

check_symbols:
  - transfer_flows_annual
