remix_parameters:
  crossover: 1
  timestart: 1
  timeend: 4
  roundts: 1
  scaletimefrac: 0

metrics:
  runtime: <=23

check_symbols:
  - transfer_caps
  - transfer_losses
  - transfer_losses_annual
