gdx_path: "c:/Local/REMix/remix_nz/project/dlr/separate-demand/result/separate-demand_wind.gdx"
geojson_path: "c:/Local/REMix/remix_nz/input/shapefiles/11regionsNZ.geojson" 
mapping_path: 

debug: False
host: 127.0.0.1
port: 5000  