gdx_path: "c:/Local/REMix/remix_nz/project/paper2/no-h2/result/no-h2_hydro-eq.gdx"
geojson_path: "c:/Local/REMix/remix_nz/input/shapefiles/11regionsNZ.geojson" 
mapping_path: 

debug: False
host: 127.0.0.1
port: 5000  